### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by r0d1337** [9tro/tokengen#3]
pog

**Comment by AmirulAndalib** [comment]
> im always getting CAPTCHA KEY IS >>>>: False
> 
> Im also getting this after False:
> 
> ```
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "C:\Users\rod\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\rod\Desktop\tokengen-main\main.py", line 154, in manager
>     register(invitecode)
>   File "C:\Users\rod\Desktop\tokengen-main\main.py", line 142, in register
>     token = registerreq.json()['token']
> KeyError: 'token'
> ```

happening to me too
